### ISSUE TITLE
[Question] Code for MEGA/OMEGA

### ISSUE THREAD

**Issue by jpuerj** [spitis/mrl#1]
Hi, I'm really impressed by the result obtained in https://arxiv.org/abs/2007.02832, congratulations. I would like to test this approach in a navigation environment with obstacles (HER fails). Can you provide the code? Thanks.

**Comment by spitis** [comment]
Hi, the experiment directory for MEGA is here: https://github.com/spitis/mrl/tree/master/experiments/mega, and the commands to actually run the experiments are in this file: https://github.com/spitis/mrl/blob/master/experiments/mega/commands_for_experiments.txt. Happy to assist further if you have difficulty adapting the code.

**Comment by jpuerj** [comment]
That's awesome, thank you for the quick (light speed) response!
