### ISSUE TITLE
[MEGA] States are not normalized before computing Q-values in goal selection

### ISSUE THREAD

**Issue by marbaga** [spitis/mrl#4]
When running with the default MEGA/OMEGA config, a state normalizer is used during policy rollouts (mrl/mrl/algorithms/continuous_off_policy.py, line 36), but it is not applied when computing Q-values of achieved goals during the behavioral goal selection procedure. I believe this would cause the Q-cutoff heuristic to malfunction. Is this an intended behavior?

**Comment by spitis** [comment]
Definitely not intended behavior! This might explain some strange behaviors we've noticed from time to time... definitely going to run some of the trickier environments it was failing on (not in the MEGA paper) with this.... thanks Marco!!
